name: Run Tests
on:
  push:

jobs:
  run_tests:
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v4
        
      - name: Install Erlang & Elixir
        uses: erlef/setup-beam@v1
        id: setup-beam
        with:
          otp-version: '26.2'
          elixir-version: '1.17.2'

      - name: Install mix dependencies
        run: mix deps.get

      - name: Check warnings
        run: mix compile --warnings-as-errors

      - name: Check formatting
        run: mix format --check-formatted

      - name: Run tests
        run: mix test
